inputs:
  geometry: runs/exp01/geometry.pt
  activations: runs/exp01/activations.h5
  teacher_vectors: runs/exp01/teacher_vectors.json
  hierarchies_json: runs/exp01/concept_hierarchies.json
logging:
  save_dir: runs/exp05b
geometry:
  lda_shrinkage: 0.10
probe:
  C: 1.0
  max_iter: 500
run:
  device: cpu
model:
  name: distilgpt2
eval:
  magnitude: 0.5
