run:
  device: cpu
model:
  name: distilgpt2
inputs:
  teacher_vectors: runs/exp01/teacher_vectors.json
  hierarchies_json: runs/exp01/concept_hierarchies.json
logging:
  save_dir: runs/exp10
geometry:
  shrinkage: 0.05
data:
  n_prompts: 50
eval:
  layers: [ -1 ]  # last hidden state index; adjust per model
