run:
  device: cpu
model:
  name: distilgpt2
inputs:
  geometry: runs/exp01/geometry.pt
  teacher_vectors: runs/exp01/teacher_vectors.json
  hierarchies_json: runs/exp01/concept_hierarchies.json
logging:
  save_dir: runs/exp10b
geometry:
  lda_shrinkage: 0.10
data:
  prompts_per_parent: 8
  prompts_per_child: 4
eval:
  layers: [-1, -2, -3, -6]
  magnitude: 0.5
