run:
  device: cpu
model:
  name: distilgpt2
inputs:
  geometry: runs/exp01/geometry.pt
  teacher_vectors: runs/exp01/teacher_vectors.json
  hierarchies_json: runs/exp01/concept_hierarchies.json
logging:
  save_dir: runs/exp06
data:
  n_prompts: 12
